---
- name: Setup User Component
  hosts: all
  become: yes
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: appuser
        system: yes
        shell: /bin/false
        create_home: no
    - name: copy user service file
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service
    - name: install node js
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
    - name: install node js
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: remove existing user app
      ansible.builtin.file:
        path: /app
        state: absent
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Download Application Content
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/user.zip
        dest: /app
        remote_src: yes

    - name: Download App Dependencies
      ansible.builtin.shell: npm install --production
      args:
        chdir: /app

    - name: Apply permission for application folder
      ansible.builtin.file:
        path: /app
        owner: appuser
        group: appuser
        recurse: yes
        mode: 'o-rwx'

    - name: Start Service
      ansible.builtin.systemd_service:
        name: user
        state: restarted
        enabled: yes
        daemon_reload: yes
